HW-02
RealThomasMiles/js-101-2020 pull request #4
Opened 2021-03-18 14:32 UTC by RealThomasMiles

Added a todo-deletion cypress test

2021-03-20 10:46 UTC, DmitryMakhnev requested changes, later dismissed
В целом всё замечательно, но есть одно небольшое замечание.

2021-03-20 10:46 UTC, DmitryMakhnev commented on 09-ts-todo-mvc-react-with-tests/tests/e2e/todos-page/manage-todos.spec.ts
> +      cy.get('[data-test-id=todo-item]').should('not.exist');
Без перехвата запроса на удаление и проверки корректности данных в нём, в данном случае тестируется только реакция интерфейса на удаление, и в случае когда в коде обработки запроса будут баги мы не узнаем о них. Поэтому данный тест без проверки корректности работы запрос ещё и затруднит поиск ошибок в функциональности удаления.

Пожалуйста, добавьте полноценный перехватчик запроса на удаление с проверкой данных в нём

2021-03-23 07:13 UTC, RealThomasMiles commented on 09-ts-todo-mvc-react-with-tests/tests/e2e/todos-page/manage-todos.spec.ts
> +      cy.get('[data-test-id=todo-item]').should('not.exist');
Вроде, что-то получилось.
Сначала хотел как-то получить id элемента непосредственно перед его удалением, чтобы потом сравнивать в запросе на удаление, но никак не получалось, поэтому решил брать его из фикстуры, где он лежит.

2021-03-27 17:23 UTC, RealThomasMiles commented on 09-ts-todo-mvc-react-with-tests/tests/e2e/todos-page/manage-todos.spec.ts
> +      cy.get('[data-test-id=todo-item]').should('not.exist');
Имелось в виду получение id элемента со страницы

2021-04-04 12:12 UTC, DmitryMakhnev approved these changes
Отлично!

2021-04-04 12:13 UTC, DmitryMakhnev commented on 09-ts-todo-mvc-react-with-tests/tests/e2e/todos-page/manage-todos.spec.ts
> +      cy.get('[data-test-id=todo-item]').should('not.exist');
Получилось хорошо. т.к. по итогу корректность проверятся, т.к. смотрим что удалился именно тот элемент, который мы дали в фикстуре

2021-04-04 12:50 UTC, merged